package com.bus.reservation.util;
import java.io.FileOutputStream;
import java.time.LocalDateTime;
import java.util.Date;

import org.springframework.stereotype.Component;

import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
@Component
public class PdfGenerator {
	 
    private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18,
            Font.BOLD);
    private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.BOLD);
    
    
    public  void generatePDF(String filePath, String firstName,String lastName, String emailId, String phone, String busNumber,String fair, LocalDateTime dateOfDeparture, String departureCity, String arrivalCity,String operatingBus,long id) {
        try {
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream(filePath));
            document.open();
            addMetaData(document);
            addTitleAndTable(document,firstName,lastName,emailId,phone,busNumber,fair, dateOfDeparture.toString(),departureCity,arrivalCity,operatingBus,id);
           
            document.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // iText allows to add metadata to the PDF which can be viewed in your Adobe
    // Reader
    // under File -> Properties
    private static void addMetaData(Document document) {
        document.addTitle("My first PDF");
        document.addSubject("Using iText");
        document.addKeywords("Java, PDF, iText");
        document.addAuthor("Lars Vogel");
        document.addCreator("Lars Vogel");
    }

    private static void addTitleAndTable(Document document, String firstName,String lastName, String emailId, String phone, String busNumber,String fair, String dateOfDeparture, String departureCity, String arrivalCity,String operatingBus,long id)
            throws DocumentException {
        Paragraph preface = new Paragraph();
        
        
        preface.add(new Paragraph("Bus Booking Details", catFont));

       
        preface.add(new Paragraph(
                "Report generated by: " + "Bus Reservation Company " + new Date(), //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
                smallBold));
       
        document.add(preface);  
        document.add( Chunk.NEWLINE );
        document.add( Chunk.NEWLINE );
        
        
        PdfPTable table = new PdfPTable(2);
        table.setWidthPercentage(100);
        // t.setBorderColor(BaseColor.GRAY);
        // t.setPadding(4);
        // t.setSpacing(4);
        // t.setBorderWidth(1);

        PdfPCell c1 = new PdfPCell(new Phrase("Passenger Detail"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        c1.setColspan(2);//merge both the columns
        table.addCell(c1);

        table.addCell("FIRST NAME");
        table.addCell(firstName);
        table.addCell("LAST NAME");
        table.addCell(lastName);
        table.addCell("EMAIL ID");
        table.addCell(emailId);
        table.addCell("PHONE NO.");
        table.addCell(phone);
        
        document.add(table);
        
        
        PdfPTable table1 = new PdfPTable(2);
        table1.setWidthPercentage(100);
        // t.setBorderColor(BaseColor.GRAY);
        // t.setPadding(4);
        // t.setSpacing(4);
        // t.setBorderWidth(1);

        PdfPCell c2 = new PdfPCell(new Phrase("Bus Details"));
        c2.setHorizontalAlignment(Element.ALIGN_CENTER);
        c2.setColspan(2);
        table1.addCell(c2);
        
        PdfPCell cell = new PdfPCell(new Phrase(Long.toString(id)));
        table1.addCell("RESERVATION ID");
        table1.addCell(cell);
        table1.addCell("BUS NUMBER");
        table1.addCell(busNumber);
        table1.addCell("OPERATING BUS");
        table1.addCell(operatingBus);
        table1.addCell("DATE OF DEPARTURE");
        table1.addCell(dateOfDeparture);
        table1.addCell("DEPARTURE CITY");
        table1.addCell(departureCity);
        table1.addCell("ARRIVAL CITY");
        table1.addCell(arrivalCity);
        table1.addCell("FAIR");
        table1.addCell(fair);
        
        document.add(table1);
       
        document.close();
    }

  
}
